---
title: "Final Project Analysis"
author: "Husayn Jessa, Sarah Kipping, Mathew Tracey, Aidan Bodner"
date: "14/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load Packages}
library(tidyverse) # load the installed package for each new session of R
library(broom) # helps for storing regression output
library(here) # for file organization
library(gtsummary) # For creating summary statistics table
library(gt) # For outputting gt objects
library(MatchIt) # For matching
library(mice) # For imputation
library(modelsummary) # For regression tables
library(VIM) # To visualize missing data
```

```{r Data Cleaning}
here() # Set working directory
raw_data <- read.csv("/Users/aidanbodner/Documents/GitHub/HAD5744-Group-Project/1. Data/data.csv", 
                     na.strings = c(" ", "", "NA", "9999: Missing")) # Load original data

analysis_data <- raw_data[, c("gad_anxious", "gad_worry", "phq_little_interest", 
                              "phq_feeling_down", "occupation","employment_impact_not_employed", 
                              "money_fetting_by","employment_impact_laid_off", "age_groups", "gender",
                              "identity_lgbtq", "identity_bipoc",
                              "educational_attainment", "income", 
                              "own_rent")]

# Scan through analysis dataframe to see variable class types
for(values in names(analysis_data)){
  print(names(analysis_data[values]))
  name <- names(analysis_data[values])
  print(class(analysis_data[,values]))
} # all variables are characters

# Remove people who were not working before the COVID-19 pandemic
analysis_data <- analysis_data[analysis_data$employment_impact_not_employed != "I was not employed or self-employed before the COVID-19", ]

# Remove people over 70
analysis_data <- analysis_data[analysis_data$age_groups != "70 to 74 years", ]
analysis_data <- analysis_data[analysis_data$age_groups != "75 to 79 years", ]
analysis_data <- analysis_data[analysis_data$age_groups != "80 to 84 years", ]

# Remove people who responded other to dwelling ownership
analysis_data <- analysis_data[analysis_data$own_rent != "Other", ]


##### Clean Labels ####

# GAD -- Over the past two weeks, how often have you felt nervous, anxious or on edge?
analysis_data$gad_anxious[analysis_data$gad_anxious == "Not at all"] <- 0
analysis_data$gad_anxious[analysis_data$gad_anxious == "Several days"] <- 1
analysis_data$gad_anxious[analysis_data$gad_anxious == "More than half the days"] <- 2
analysis_data$gad_anxious[analysis_data$gad_anxious == "Nearly every day"] <- 3

analysis_data$gad_anxious <- as.numeric(analysis_data$gad_anxious)

# GAD -- Over the past two weeks, how often were you not able to stop worrying or control your worries?
analysis_data$gad_worry[analysis_data$gad_worry == "Not at all"] <- 0
analysis_data$gad_worry[analysis_data$gad_worry == "Several days"] <- 1
analysis_data$gad_worry[analysis_data$gad_worry == "More than half the days"] <- 2
analysis_data$gad_worry[analysis_data$gad_worry == "Nearly every day"] <- 3

analysis_data$gad_worry <- as.numeric(analysis_data$gad_worry)

# Create new combined GAD score
analysis_data$gad_total <- analysis_data$gad_anxious + analysis_data$gad_worry

# PHQ -- Over the past two weeks, how often have you had little interest or pleasure in doing things?
analysis_data$phq_feeling_down[analysis_data$phq_feeling_down == "Not at all"] <- 0
analysis_data$phq_feeling_down[analysis_data$phq_feeling_down == "Several days"] <- 1
analysis_data$phq_feeling_down[analysis_data$phq_feeling_down == "More than half the days"] <- 2
analysis_data$phq_feeling_down[analysis_data$phq_feeling_down == "Nearly every day"] <- 3

analysis_data$phq_feeling_down <- as.numeric(analysis_data$phq_feeling_down)

# PHQ -- Over the PAST TWO WEEKS, how often were you feeling down, depressed or hopeless?
analysis_data$phq_little_interest[analysis_data$phq_little_interest == "Not at all"] <- 0
analysis_data$phq_little_interest[analysis_data$phq_little_interest == "Several days"] <- 1
analysis_data$phq_little_interest[analysis_data$phq_little_interest == "More than half the days"] <- 2
analysis_data$phq_little_interest[analysis_data$phq_little_interest == "Nearly every day"] <- 3

analysis_data$phq_little_interest <- as.numeric(analysis_data$phq_little_interest)

# Create new combined PHQ score
analysis_data$phq_total <- analysis_data$phq_feeling_down + analysis_data$phq_little_interest


# Occupation
analysis_data$occupation[analysis_data$occupation == "Business, finance and administration occupations"] <- "Business & Management"
analysis_data$occupation[analysis_data$occupation == "Management occupations"] <- "Business & Management"
analysis_data$occupation[analysis_data$occupation == "Natural resources, agriculture and related production occupations" ] <- "Trades"

analysis_data$occupation[analysis_data$occupation == 
                           "Occupations in manufacturing and utilities"] <- "Trades"

analysis_data$occupation[analysis_data$occupation == "Trades, transport and equipment operators and related occupations" ] <- "Trades"



analysis_data$occupation[analysis_data$occupation == "Health occupations" ] <- "Health & Sciences"

analysis_data$occupation[analysis_data$occupation == 
                           "Natural and applied sciences and related occupationss"] <- "Health & Sciences"

# How well do each of the statements describe you? - I am just getting by financially.
analysis_data$money_fetting_by[analysis_data$money_fetting_by == "Completely"] <- "Yes"
analysis_data$money_fetting_by[analysis_data$money_fetting_by == "Very Well"] <- "Yes"
analysis_data$money_fetting_by[analysis_data$money_fetting_by == "Somewhat"] <- "Yes"
analysis_data$money_fetting_by[analysis_data$money_fetting_by == "Not at all"] <- "No"
analysis_data$money_fetting_by[analysis_data$money_fetting_by == "Very Little"] <- "No"

# Age
analysis_data$age_groups[analysis_data$age_groups == "16 to 19 years" 
                           ] <- "16 to 24 years"
analysis_data$age_groups[analysis_data$age_groups == 
                           "20 to 24 years"] <- "16 to 24 years"


analysis_data$age_groups[analysis_data$age_groups == "25 to 29 years" ] <- "25 to 39 years"


analysis_data$age_groups[analysis_data$age_groups == "30 to 34 years"] <- "25 to 39 years"


analysis_data$age_groups[analysis_data$age_groups == 
                           "35 to 39 years"] <- "25 to 39 years"

analysis_data$age_groups[analysis_data$age_groups == "40 to 44 years" ] <- "40 to 54 years"

analysis_data$age_groups[analysis_data$age_groups == 
                           "45 to 49 years"] <- "40 to 54 years"

analysis_data$age_groups[analysis_data$age_groups == 
                           "50 to 54 years"] <- "40 to 54 years"

analysis_data$age_groups[analysis_data$age_groups == "55 to 59 years" ] <- "55 to 69 years"

analysis_data$age_groups[analysis_data$age_groups == 
                           "60 to 64 years" 
                          ] <- "55 to 69 years"

analysis_data$age_groups[analysis_data$age_groups == 
                           "65 to 69 years"] <- "55 to 69 years"

# Educational attainment -- TO BE COMPLETED

# Income


analysis_data$income[analysis_data$income == "Under $5,000" ] <- "Low-Income"
analysis_data$income[analysis_data$income == "$5,000 to $9,999" ] <- "Low-Income"
analysis_data$income[analysis_data$income == "$10,000 to $14,999" ] <- "Low-Income"
analysis_data$income[analysis_data$income == "$15,000 to $19,999" ] <- "Low-Income"
analysis_data$income[analysis_data$income == "$20,000 to $24,999" ] <- "Low-Income"
analysis_data$income[analysis_data$income == "$25,000 to $29,999" ] <- "Low-Income"
analysis_data$income[analysis_data$income == "$30,000 to $34,999" ] <- "Low-Income"
analysis_data$income[analysis_data$income == "$35,000 to $39,999" ] <- "Low-Income"
analysis_data$income[analysis_data$income == "$40,000 to $44,999" ] <- "Low-Income"
analysis_data$income[analysis_data$income == "$45,000 to $49,999" ] <- "Low-Income"
analysis_data$income[analysis_data$income == "$50,000 to $59,999" ] <- "Low-Income"



analysis_data$income[analysis_data$income == "$60,000 to $69,999" ] <- "Middle-Income"
analysis_data$income[analysis_data$income == "$70,000 to $79,999" ] <- "Middle-Income"
analysis_data$income[analysis_data$income == "$80,000 to $89,999" ] <- "Middle-Income"
analysis_data$income[analysis_data$income == "$90,000 to $99,999" ] <- "Middle-Income"



analysis_data$income[analysis_data$income == "$100,000 to $149,999" ] <- "High-Income"
analysis_data$income[analysis_data$income == "$150,000 to $199,999" ] <- "High-Income"
analysis_data$income[analysis_data$income == "$200,000 or more" ] <- "High-Income"



# Dwelling Ownership
analysis_data <- mutate_at(.tbl = analysis_data, 
                                .vars = vars(own_rent), 
                                .funs = ~case_when(. == "Own it with mortgage or loan (including condos)" ~ "Cost Incurred from Housing", 
                                                   . == "Rent it without subsidies, i.e. you pay a market rate" ~ "Cost Incurred from Housing", 
                                                   . == "Part own and part rent (shared ownership such as co-op)" ~ "Cost Incurred from Housing, Subsidized", 
                                                   . == "Rent it with subsidies, i.e. you pay a below-market rate (including rent geared to income, social housing, government assisted housing, housing allowances, etc.)" ~ "Cost Incurred from Housing, Subsidized", 
                                                   . == "Own it outright (including condos)" ~ "No Cost Incurred from Housing",
                                                   . == "Rent at no costs, i.e. rent-free in relative\x92s/friend\x92s property\\" ~ "No Cost Incurred from Housing",
                                                   TRUE ~ .,
                                                   TRUE ~ as.character(NA_character_)))


# Laid off during COVID
analysis_data$employment_impact_laid_off[analysis_data$employment_impact_laid_off == "8888: Not Selected"] <- "No"
analysis_data$employment_impact_laid_off[analysis_data$employment_impact_laid_off == "I was laid off temporarily or permanently"] <- "Yes"


# Sexual minority
analysis_data$identity_lgbtq[analysis_data$identity_lgbtq == "8888: Not Selected"] <- "No"
analysis_data$identity_lgbtq[analysis_data$identity_lgbtq == "Sexual or gender minorities (e.g., LGBTQ2+)"] <- "Yes"

# People of Colour
analysis_data$identity_bipoc[analysis_data$identity_bipoc == "8888: Not Selected"] <- "No"
analysis_data$identity_bipoc[analysis_data$identity_bipoc == "People of colour (e.g., Black, Indigenous, Asian  or other racialized minority)"] <- "Yes"





analysis_data <- analysis_data[, c("gad_total", "phq_total", "occupation","employment_impact_laid_off", "age_groups", "gender", "identity_lgbtq", "identity_bipoc","income", "own_rent", "money_fetting_by")]

# Number of missing
#analysis_data <- na.omit(analysis_data)




```


```{r}
analysis_data$occupation <- as.factor(analysis_data$occupation)
analysis_data$money_fetting_by <- as.factor(analysis_data$money_fetting_by)
analysis_data$age_groups <- as.factor(analysis_data$age_groups)
analysis_data$gender <- as.factor(analysis_data$gender)
analysis_data$identity_lgbtq <- as.factor(analysis_data$identity_lgbtq)
analysis_data$identity_bipoc <- as.factor(analysis_data$identity_bipoc)
analysis_data$income <- as.factor(analysis_data$income)
analysis_data$own_rent <- as.factor(analysis_data$own_rent)
analysis_data$employment_impact_laid_off <- as.factor(analysis_data$employment_impact_laid_off)





imputed_data <- mice(analysis_data, m = 5, maxit=50, method='pmm')
impute_convert <- complete(imputed_data)

write.csv(impute_convert, "/Users/aidanbodner/Documents/GitHub/HAD5744-Group-Project/1. Data/imputed_data.csv")

analysis_data <- read.csv("/Users/aidanbodner/Documents/GitHub/HAD5744-Group-Project/1. Data/imputed_data.csv")

```



```{r Summary Statistics}

analysis_data$money_fetting_by <- as.factor(analysis_data$money_fetting_by)
analysis_data$money_fetting_by <- relevel(analysis_data$money_fetting_by, ref = "Yes")

summary_table_1 <- tbl_summary(analysis_data, include = c("gad_total", "phq_total", "occupation",
                                                        "money_fetting_by", "age_groups", "employment_impact_laid_off",
                                                        "gender", "identity_lgbtq", "identity_bipoc", "income", "own_rent"),
                             label = list(gad_total ~ "GAD Score",
                                          money_fetting_by ~ "I am just getting by financially",
                                          employment_impact_laid_off ~ "Laid off temporarily or permanently during COVID-19 Pandemic",
                                          phq_total ~ "PHQ Score",
                                          occupation ~ "Occupation",
                                          age_groups ~ "Age", 
                                          gender ~ "Gender", 
                                          identity_lgbtq ~ "Sexual or gender minority (e.g., LGBTQ2+)",
                                          identity_bipoc ~ "Person of colour (e.g., Black, Indigenous, Asian  or other racialized minority)",
                                          income ~ "Income",
                                          own_rent ~ "Dwelling Ownership"),
                             value = list(money_fetting_by ~ "No"),
                             missing = "no", 
                             type = list(identity_lgbtq ~ "categorical",
                                         identity_bipoc ~ "categorical",
                                         occupation ~ "categorical",
                                         age_groups ~ "categorical",
                                         income ~ "categorical",
                                         own_rent ~ "categorical",
                                         gender ~ "categorical"))




summary_table_2 <- tbl_summary(analysis_data, include = c("gad_total", "phq_total", "occupation",
                                                        "money_fetting_by", "age_groups", "employment_impact_laid_off",
                                                        "gender", "identity_lgbtq", "identity_bipoc", "income", "own_rent"),
                             by = employment_impact_laid_off,
                             label = list(gad_total ~ "GAD Score",
                                          money_fetting_by ~ "I am just getting by financially",
                                          phq_total ~ "PHQ Score",
                                          occupation ~ "Occupation",
                                          age_groups ~ "Age", 
                                          gender ~ "Gender", 
                                          identity_lgbtq ~ "Sexual or gender minority (e.g., LGBTQ2+)",
                                          identity_bipoc ~ "Person of colour (e.g., Black, Indigenous, Asian  or other racialized minority)",
                                          income ~ "Income",
                                          own_rent ~ "Dwelling Ownership"),
                             value = list(money_fetting_by ~ "No"), 
                             missing = "no", 
                             type = list(identity_lgbtq ~ "categorical",
                                         identity_bipoc ~ "categorical",
                                         occupation ~ "categorical",
                                         age_groups ~ "categorical",
                                         income ~ "categorical",
                                         own_rent ~ "categorical",
                                         gender ~ "categorical"))

summary_table <- tbl_merge(tbls = list(summary_table_1,
                                      summary_table_2)) %>%
  as_gt %>%
  gt::gtsave(file = "//Users//aidanbodner//Desktop//summary_table.docx")




```


```{r Matching}
analysis_match <- matchit(employment_impact_laid_off ~ occupation + age_groups + gender + identity_lgbtq +
                            identity_bipoc + income + own_rent,
                            data = analysis_data,
                            method = "exact")
summary(analysis_match)
analysis_match_data <-  match.data(analysis_match)



unmatched_table <- tbl_summary(analysis_data, include = c("occupation", "employment_impact_laid_off",
                                                        "money_fetting_by", "age_groups", 
                                                        "gender", "identity_lgbtq", "identity_bipoc", "income", "own_rent"),
                             by = employment_impact_laid_off,
                             label = list(occupation ~ "Occupation",
                                          money_fetting_by ~ "I am just getting by financially.",
                                          age_groups ~ "Age", 
                                          gender ~ "Gender", 
                                          identity_lgbtq ~ "Sexual or gender minority (e.g., LGBTQ2+)",
                                          identity_bipoc ~ "Person of colour (e.g., Black, Indigenous, Asian  or other racialized minority)",
                                          income ~ "Income",
                                          own_rent ~ "Dwelling Ownership"), 
                             missing = "no", 
                             type = list(identity_lgbtq ~ "categorical",
                                         identity_bipoc ~ "categorical",
                                         occupation ~ "categorical",
                                         age_groups ~ "categorical",
                                         income ~ "categorical",
                                         own_rent ~ "categorical",
                                         gender ~ "categorical",
                                         money_fetting_by ~ "categorical")) %>% 
  add_p(test = everything() ~ "fisher.test")



match_table <- tbl_summary(analysis_match_data, include = c("occupation", "employment_impact_laid_off",
                                                        "money_fetting_by", "age_groups", 
                                                        "gender", "identity_lgbtq", "identity_bipoc", "income", "own_rent"),
                             by = employment_impact_laid_off,
                             label = list(occupation ~ "Occupation",
                                          money_fetting_by ~ "I am just getting by financially.",
                                          age_groups ~ "Age", 
                                          gender ~ "Gender", 
                                          identity_lgbtq ~ "Sexual or gender minority (e.g., LGBTQ2+)",
                                          identity_bipoc ~ "Person of colour (e.g., Black, Indigenous, Asian  or other racialized minority)",
                                          income ~ "Income",
                                          own_rent ~ "Dwelling Ownership",
                                          money_fetting_by ~ "I am just getting by financially"),
                             missing = "no", 
                             type = list(identity_lgbtq ~ "categorical",
                                         identity_bipoc ~ "categorical",
                                         occupation ~ "categorical",
                                         age_groups ~ "categorical",
                                         income ~ "categorical",
                                         own_rent ~ "categorical",
                                         gender ~ "categorical",
                                         money_fetting_by ~ "categorical")) %>% 
  add_p(test = everything() ~ "fisher.test")


balance_table <- tbl_merge(tbls = list(unmatched_table,
                                      match_table),
                          tab_spanner = c("UnMatched Balance Table",
                                          "Nearest Neighbour Matched Balance Table")) %>%
  as_gt %>%
  gt::gtsave(file = "//Users//aidanbodner//Desktop//balance_table.rtf")




```



```{r Regression}
# Check to see if models are different including matched variables as covariates in the regression

analysis_match_data$money_fetting_by <- as.factor(analysis_match_data$money_fetting_by)
analysis_match_data$money_fetting_by <- relevel(analysis_match_data$money_fetting_by, ref = "Yes")

phq_lm <- lm(phq_total ~ employment_impact_laid_off + employment_impact_laid_off:money_fetting_by, data = analysis_match_data)

phq_lm_w_cov <- lm(phq_total ~ employment_impact_laid_off + employment_impact_laid_off:money_fetting_by + occupation + age_groups + gender + identity_lgbtq + identity_bipoc + income + own_rent, data = analysis_match_data)

summary(phq_lm)
summary(phq_lm_w_cov)


gad_lm <- lm(gad_total ~ employment_impact_laid_off + employment_impact_laid_off:money_fetting_by, data = analysis_match_data)
gad_lm_w_cov <- lm(gad_total ~ employment_impact_laid_off + employment_impact_laid_off:money_fetting_by + occupation + age_groups + gender + identity_lgbtq + identity_bipoc + income + own_rent, data = analysis_match_data)

summary(gad_lm)
summary(gad_lm_w_cov)

msummary(models = list("PHQ-2" = phq_lm, 
                       "GAD-2" = gad_lm),
         stars=c('*' = .1, '**' = .05, '***' = .01),
         output = "//Users//aidanbodner//Desktop//regression_table.rtf")


#the regressions including the covariates and excluding them look similar and thus it can be noted that our match is of sufficient quality to run the regression without including the covariates 
```


```{r Summary Stats by MH}

analysis_match_data$gad_clinical_cut <- ifelse(analysis_match_data$gad_total >= 3,1,0) #creating a binary variable based on the clinical cut off of GAD-2
analysis_match_data$phq_clinical_cut <- ifelse(analysis_match_data$phq_total >= 3,1,0)
 
gad_table <- table(analysis_match_data$money_fetting_by, analysis_match_data$gad_clinical_cut, analysis_match_data$employment_impact_laid_off)

prop.table(gad_table, 1)*100
gad_mantel <- mantelhaen.test(gad_table)
 


phq_table <- table(analysis_match_data$money_fetting_by, analysis_match_data$phq_clinical_cut, analysis_match_data$employment_impact_laid_off)

prop.table(phq_table, 1)*100
phq_mantel <- mantelhaen.test(phq_table)

```


```{r Figures}
# Missing data
aggplot <- aggr(analysis_data, cex.axis = .385)
 
# Outcome histograms
fig1 <- ggplot(analysis_data, aes(gad_total,group=employment_impact_laid_off,fill=employment_impact_laid_off)) +
  geom_histogram(binwidth = 1,alpha = 0.75) + theme_classic() +
  labs(x = "GAD-2 Total Score", fill = "Laid Off")
 
fig2 <- ggplot(analysis_data, aes(phq_total, group=employment_impact_laid_off,fill=employment_impact_laid_off)) +
  geom_histogram(binwidth = 1,alpha = 0.75) + theme_classic() +
  labs(x = "PHQ-2 Total Score", fill = "Laid Off")


ggsave(plot = fig1, filename  = "//Users//aidanbodner//Desktop//GAD-2.png", dpi = 700)
ggsave(plot = fig2, filename  = "//Users//aidanbodner//Desktop//PHQ-2.png", dpi = 700)
 


```



